version: 0.0
os: linux
files:
  - source: /static/admin
    destination: /var/www
    runas: ubuntu
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh




