version: 0.0
os: linux
files:
  - source: $(pwd)
    destination: /usr/local/bin/myproject
  - source: $(pwd)
    destination: /etc/apache2/sites-available/000-default.conf
    runas: ubuntu
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh




