version: 0.2
name: Python application
phases:
  pre_build:
    commands:
      - apt-get update
      - apt upgrade -y
      - apt-get install python3 -y
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --user virtualenv
  build:
    commands:
      - virtualenv myenv
      - pip3 install knox
      - pip3 install -r requirements.txt
      - python3 manage.py migrate
      - python3 manage.py collectstatic --no-input
      - cp -a $(pwd) /usr/local/bin/myproject
      - chmod 777 /usr/local/bin/myproject/db.sqlite3
      - chown :www-data /usr/local/bin/myproject/db.sqlite3
      - chmod 777 /usr/local/bin/myproject
      - chown :www-data /usr/local/bin/myproject
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo $(pwd)
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
        
