version: 0.2
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

phases:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install python3 -y
        sudo apt install supervisor -y
        sudo apt-get install apache2 libapache2-mod-wsgi-py3
        python3 -m pip install --upgrade pip
        python3 -m pip install --user virtualenv
        
    - name: mystep
      run: |
        sudo cp -a $(pwd) /usr/local/bin/myproject
        cd usr/local/bin/myproject
        virtualenv myenv
        source myenv/bin/activate
        pip3 install knox
        pip3 install -r requirements.txt
        python3 manage.py migrate
        python3 manage.py collectstatic
        sudo cp 000-default.conf /etc/apache2/sites-available/000-default.conf
        sudo service apache2 restart
        cd /usr/local/bin/myproject/
        sudo chmod 777 db.sqlite3
        sudo chown :www-data db.sqlite3
        cd /usr/local/bin/
        sudo chmod 777 myproject
        sudo chown :www-data /usr/local/bin/myproject
        sudo service apache2 restart
        